name: Docker Image CI - Hello World

on:   
  push:
    # trigger workflow when these branches are being pushed to
    branches:    
      - master         # Push events on master branch

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Display the IMAGE_NAME
      run: echo ${env:DOCKER_REPO}
      shell: bash
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.build --tag $DOCKER_REPO:${GITHUB_SHA::8}
      env:
        DOCKER_REPO: airspacesystems/hello-world-github-actions
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push image
      run: docker push ${DOCKER_REPO}:${GITHUB_SHA::8}
