name: Docker Image CI - Hello World - Tag Yml

on:   
  push:
    # trigger workflow when these branches are being pushed to
    tags:
      - v*

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Actions Checkout (with tag)
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        
    - name: Echo check (with tag)
      env:
        DOCKER_REPO: julam5/hello-world-github-actions
        GITHUB_REF_PREFIX: refs/tags/
      run: echo ${GITHUB_REF#${GITHUB_REF_PREFIX}}
      
    #- name: Build the Docker image (with tag)
    #  env:
    #    DOCKER_REPO: julam5/hello-world-github-actions
    #  run: docker build . --file Dockerfile.build --tag $DOCKER_REPO:${GITHUB_REF} 
  
  
  
    #- name: Login to DockerHub Registry
    #  run: echo "${{ secrets.PERSONAL_DOCKER_PASSWORD }}" | docker login -u ${{ secrets.PERSONAL_DOCKER_USERNAME }} --password-stdin
      
      
    #- name: Push image (with tag)
    #  env:
    #    DOCKER_REPO: julam5/hello-world-github-actions
    #  run: docker push ${DOCKER_REPO}:${GITHUB_REF}
      
      
      
