name: Docker Image CI - Hello World

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Display the path
      run: echo $PATH
      shell: bash
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.build --tag my-image-name:${GITHUB_SHA::8}
