name: Docker Image CI - Hello World

on:   
  push:
    # trigger workflow when these branches are being pushed to
    branches:    
      - master         # Push events on master branch

jobs:

  build-job:
    env:
      IMAGE_NAME: airspacesystems/airspacecommon
    runs-on: ubuntu-latest
    steps:
    - name: Display the IMAGE_NAME
      run: echo ${env:IMAGE_NAME}
      shell: bash
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.build --tag my-image-name:${GITHUB_SHA::8}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: airspacesystems/hello-world-github-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.build
