name: Docker Image CI - Hello World

on:   
  push:
    # trigger workflow when these branches are being pushed to
    tags:    
      - v*         # Push events on master branch

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${GITHUB_REF}
    - name: Build the Docker image
      run: docker build . --file Dockerfile.build --tag $DOCKER_REPO:${GITHUB_REF}
      env:
        DOCKER_REPO: julam5/hello-world-github-actions
    - name: Login to DockerHub Registry
      run: echo "${{ secrets.PERSONAL_DOCKER_PASSWORD }}" | docker login -u ${{ secrets.PERSONAL_DOCKER_USERNAME }} --password-stdin
    - name: Push image
      run: docker push ${DOCKER_REPO}:${GITHUB_REF}
      env:
        DOCKER_REPO: julam5/hello-world-github-actions
